src/main/java/pl/project13/maven/git/JGitProvider.java, src/main/java/pl/project13/maven/git/NativeGitProvider.java, src/test/java/pl/project13/maven/git/FileSystemMavenSandbox.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java, src/test/java/pl/project13/maven/git/NativeAndJGitProviderTest.java
On my box (using git 1.9.3), for a small project, there are the
following differences between jgit and native output:
```
field                   | jgit                       | native
git.build.user.name     | Henning Schmiedehausen     | "Henning Schmiedehausen"
git.build.user.email    | henning@schmiedehausen.org | "henning@schmiedehausen.org"
git.dirty               | true                       | false
git.commit.user.name    | Henning Schmiedehausen     | "Henning Schmiedehausen"
git.commit.user.email   | henning@schmiedehausen.org | "henning@schmiedehausen.org"
git.commit.message.full | Create README.md           | "Create README.md"
git.commit.message.short| Create README.md           | "Create README.md"
git.commit.time         | 2014-11-21T18:47:34-0800   | "2014-11-21 18:47:34 …
```
=> Fix differences in the output of native and jgit

src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
fixes https://github.com/ktoso/maven-git-commit-id-plugin/issues/108 by only overwriting properties which are set by the maven-git-commit-id-plugin. Also disables the propagation of properties by default.
=> only propagate git properties to other maven modules

src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
finally had some time to fix the possible NPE in https://github.com/ktoso/maven-git-commit-id-plugin/issues/153. Does not seem to hurt to add some more parameters here.
In #153 there was also a deprecation warning which had already been fixed by
https://github.com/ktoso/maven-git-commit-id-plugin/commit/f4fa04feb089e73e7ddffe646c83e1f716e8b858
=> Fix for possible NPE as discussed in #153

src/main/java/pl/project13/maven/git/JGitProvider.java
revWalk.parseCommit will throw a NPE when Argument is null.
```
Caused by: java.lang.NullPointerException
at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
at pl.project13.maven.git.JGitProvider.prepareGitToExtractMoreDetailedReproInformation(JGitProvider.java:91)
... 26 more
```
=> Avoid NPE as discussed in #57

README.md
Missed one place to add the property in readme.md
=> Add missing git.build.host to GitRepositoryState Bean

README.md, pom.xml
As suggested in https://github.com/ktoso/maven-git-commit-id-plugin/issues/181, I would like to introduce a demo-Profile where anybody can just run the plugin right away.
This would speed up to live test wheather something is broken under some conditions or not. I used this in one of my own plugins to discover some nasty bugs.
However, this will not avoid writing Testcases. This should only help to track down a problem and then writing test cases for it.
For my own plugin I once had included it in the regular-build (so run everytime for everytime), However when i screwed up, I had no chance to re run ``mvn clean install`` without removing the config of the plugin. Therefore I needed to moved it to a different profile where I could choose if I would like to run it or not.
=> Introduce a demo-profile inside the pom, see #181

.travis.yml, README.md
Hi @ktoso,
I just tried to clean-up the readme a bit.
I rearranged a lot of things and therefore it seems to be a bit bigger PR.
I also readded the travis tests for java 6. I think as long as we support java we should include them....I'll create a ticket do drop this.
=>  getting the readme back to business; added injectAllReactorProjects to the docs

README.md, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoTest.java
Hello Konrad,
I'm a user of your plugin and I thought it might be useful to add the two parameters I did. They allow a little bit more flexibility and then to put everything in a same file for instance.
In my case I needed only this configuration:
<configuration>
<dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
<generateGitPropertiesFile>true</generateGitPropertiesFile>
<generateGitPropertiesFilename>src/main/resources/myAppInfo.properties</generateGitPropertiesFilename>
<includeProperties>
<includeProperty>^git.commit.id$</includeProperty>
</includeProperties>
<additionalProperties>
<buildVersion>${project.version}</buildVersion>
</additionalProperties>
<verbose>true</verbose>
</configuration>
Tell me if it's okay or if I need to change something.
Regards,
Marc
=> Added includeProperties and additionalProperties as mojo parameters.

pom.xml, src/main/java/pl/project13/maven/git/log/MavenLoggerBridge.java, src/test/java/pl/project13/maven/git/log/MavenLoggerBridgeTest.java
I'm just created the PR. 
Its way too late to actually pull this right in the repo...:-)
I also override some simple-logger's default properties to look like the normal maven log outpout. However those can still be overriden by setting -Dorg.slf4j.simpleLogger.showThreadName=true.
Link to issue: https://github.com/ktoso/maven-git-commit-id-plugin/issues/191
=> Fix for #191 slf4j simple-logger for logging

pom.xml
currently only need to include org.slf4j in the uber-jar
=> fix for 196: create a uber-jar as a workaround for maven's class loading problem (MNG-5787)

README.md, pom.xml, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/main/java/pl/project13/maven/git/JGitProvider.java, src/main/java/pl/project13/maven/git/NativeGitProvider.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java
As described in https://github.com/ktoso/maven-git-commit-id-plugin/issues/204 added the ability to set the timezone along with dateFormat.
I hopefully made it crystal clear in the docs that setting the timeZone in the plugin's configuration will override any other configuration.
The reason for this, is that we can not determine at which level the user has altered the timezone of java or the system. It could be in some configuration file or by setting runtime environment parameters like ``-Duser.timezone=UTC``. If we investigate the system properties of java, we only see the latest version that was set. At this moment java does not simply ship an option to determine where the timezone was altered. Also I didn't want to introduce some garbage code that invokes a process builder that asks …
=> Fix for #204

README.md, src/main/java/pl/project13/maven/git/CommitIdGenerationModeEnum.java, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/java/pl/project13/maven/git/log/LoggerBridge.java, src/main/java/pl/project13/maven/git/log/MavenLoggerBridge.java, src/main/java/pl/project13/maven/git/log/StdOutLoggerBridge.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoTest.java, src/test/java/pl/project13/maven/git/GitIntegrationTest.java
As outlined in #211 I think this is much better for the generation "git.commit.id" VS "git.commit.id.full".
Have tested with different options and build in parallel (mvn -T 4 clean package -Pdemo -Dmaven.test.skip=true) nothing special discovered.
=> #211 : add a switch to generate the git.commit.id the "old" way

src/main/java/pl/project13/maven/git/GitDataProvider.java, src/main/java/pl/project13/maven/git/JGitProvider.java, src/main/java/pl/project13/maven/git/NativeGitProvider.java, src/test/java/pl/project13/maven/git/UriUserInfoRemoverTest.java
=> Added code to ensure that passwords are not included git.remote.origin.url

src/main/java/pl/project13/maven/git/GitDataProvider.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoTest.java
The current release version of the maven-git-commit-id-plugin resolves the branch name from GIT_BRANCH if it detects a Jenkins / Hudson environment.
In version 2.4.3 of the Git Plugin for Jenkins / Hudson support for deriving local branch names from remote branch names was added. The name for the derived local branch is exposed in the GIT_LOCAL_BRANCH environment variable.
https://issues.jenkins-ci.org/browse/JENKINS-33202
https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin
The changes in this pull request should add support for the new derived local branch.
=> Support GIT_LOCAL_BRANCH in Jenkins / Hudson

README.md
Proposed solution for issue (only documentation) #260
Please review
=> Describe the subtle shift in meaning of git.build.time when generated into git.properties.

src/main/java/pl/project13/jgit/DescribeCommand.java
If an exception occurs while getting the commits in the JGit describe command implementation, and the always flag is set, show the uniquely abbreviated commit object as fallback matching the native git command's behavior.
This change fixes #61 
To see this issue, run this plugin against a shallow clone (`git clone --depth 1`) that has multiple commits with the configuration of this plugin having:
```xml
<configuration>
<gitDescribe>
<always>true</always>
</gitDescribe>
</configuration>
```
Before this change, this exception occurs:
```
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.2:revision (default) on project mindsight: Could not complete Mojo execution... Unable to find commits until some tag: Walk failure. Missing commit …
```
=> Fix support the always flag for the describe command in JGit in shallow clones

.travis.yml, README.md, pom.xml
This Refs to https://github.com/ktoso/maven-git-commit-id-plugin/issues/316
Local tests with
```
#!/bin/bash
for mavenBasePath in /usr/share/maven-3*
do
echo "============================================"
${mavenBasePath}/bin/mvn --version
echo ""
for pluginVersion in 2.2.4-SNAPSHOT
do
rm -rf target
echo "${mavenBasePath}/bin/mvn pl.project13.maven:git-commit-id-plugin:${pluginVersion}:revision"
${mavenBasePath}/bin/mvn pl.project13.maven:git-commit-id-plugin:${pluginVersion}:revision -Pdemo > /dev/null
rc=$?;
if [[ $rc != 0 ]]; then
echo "pl.project13.maven:git-commit-id-plugin:${pluginVersion} is NOT compatible";
else
echo "pl.project13.maven:git-commit-id-plugin:${pluginVersion} is compatible"
fi
echo ""
cat target/testing.properties | sed 's/\(.*\)/  \1/'
done
done
```
didn't yield …
=> Support Maven 3.X

README.md, pom.xml, src/main/java/pl/project13/maven/git/TransformationRule.java
=> Minor fixes for #317

.travis.yml
Build Stages allow to group the build into different categories (similar to a pipeline).
I think this a feature we can make a use of since we kinda have two sets of tests. The first set of tests is the normal integration test and the second set is the matrix build that is currently performing a full integration test with various maven versions. Travis new feature of build stages pretty much helps us to group those into different categories. By default all the normal tests (`mvn clean package`) are executed in parallel. However if those tests fail it would be a waste of resources to also run the full integration tests (`mvn clean install && mvn clean initialize -Pdemo`) since we already know something is broken. The build pretty much only advances to the next build stage if the current …
=> Introduce new travis beta-feature of Build Stages 

.github/ISSUE_TEMPLATE.md, .travis.yml, README.md, pom.xml, src/main/java/pl/project13/jgit/DescribeCommand.java, src/main/java/pl/project13/jgit/JGitCommon.java, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/main/java/pl/project13/maven/git/JGitProvider.java, src/main/java/pl/project13/maven/git/NativeGitProvider.java, src/test/java/pl/project13/jgit/DescribeCommandAbbrevIntegrationTest.java, src/test/java/pl/project13/jgit/DescribeCommandIntegrationTest.java, src/test/java/pl/project13/jgit/DescribeCommandOptionsTest.java, src/test/java/pl/project13/jgit/DescribeCommandTagsIntegrationTest.java, src/test/java/pl/project13/maven/git/AvailableGitTestRepo.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoTest.java, src/test/java/pl/project13/maven/git/GitIntegrationTest.java
This is a combined merge request for the following:
- #337: Create an Issue Template 
- #338: add an option to specify branch/tag/commit used when finding 'HEAD'
- add maven 3.5.2 to travis integrations tests 
- move (integration) tests from GitCommitIdMojoTest to GitCommitIdMojoIntegrationTest
- #339: git.tags yields wrong results for JGit
=> Adressing #337, #338, #339 and other minor improvements

README.md, src/main/java/pl/project13/jgit/dummy/DatedRevTag.java
=> fix  #341 (NullPointerException at pl.project13.jgit.dummy.DatedRevTag) and adding readme section about mvn install/deploy

src/main/java/pl/project13/maven/git/GitCommitPropertyConstant.java, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/main/java/pl/project13/maven/git/GitProvider.java, src/main/java/pl/project13/maven/git/JGitProvider.java, src/main/java/pl/project13/maven/git/NativeGitProvider.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java, src/test/java/pl/project13/maven/git/NativeAndJGitProviderTest.java, src/test/resources/checks/checkstyle-suppressions.xml
refs:
- https://github.com/ktoso/maven-git-commit-id-plugin/issues/352
- https://github.com/ktoso/maven-git-commit-id-plugin/pull/345
=> #352 / #345 : add total commit count property via 'rev-list <commit> --count'

src/main/java/pl/project13/maven/git/NativeGitProvider.java
The current NativeGitProvider waits for the git process to be finished before it starts reading the output. This can cause a deadlock on some systems where the buffer size is smaller than the git output, for example when there are a lot of git tags.
Here is the documentation of [Process](https://docs.oracle.com/javase/7/docs/api/java/lang/Process.html) for reference:
> The parent process uses these streams to feed input to and get output from the subprocess. Because some native platforms only provide limited buffer size for standard input and output streams, failure to promptly write the input stream or read the output stream of the subprocess may cause the subprocess to block, or even deadlock.
=> Read the output of native git before waiting for it to complete

.travis.yml
the current version seems to already work with java 11
https://travis-ci.org/TheSnoozer/maven-git-commit-id-plugin/jobs/421822610
```
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
i would say that should be sufficient to say the current version supports java 11. I can remember that java 9 caused more headaches with incompatible plugins....
=> #379: Add tests for Java 11

pom.xml, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
This may fix issue #366 while still respecting performance concerns from #269.
It use a BuildContext as described in [m2e](https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html#buildcontext) to distinguish between incremental and normal (e.g. mvn command line) builds. On incremental builds it should only run if the git.properties file is missing at all.
Additional the BuildContext can inform eclipse about the new generated file. (especially useful if file is generated in some folder not ignored by the IDE)
=> run on eclipse incremental build if properties file was not generated

pom.xml
Support jgit 5.1.1 release.  Currently this plugin is using httpclient which was a transient dependency of jgit.  That transient is no longer present.  Therefore, for continued usage, a simple change to include the httpclient along with jgit 5.1.1 works without issue.  Additionally updated mockito/junit/jackson to latest releases.  All changes isolated to pom only.
- [ N/A] Added relevant integration or unit tests to verify the changes
- [ N/A] Update the Readme or any other documentation (including relevant Javadoc)
- [ X] Ensured that tests pass locally: `mvn clean package`
- [ N/A] Ensured that the code meets the current `checkstyle` coding style definition: `mvn clean verify -Pcheckstyle -Dmaven.test.skip=true -B`
=> Support jgit 5.1.1, add direct httpclient, and update dependencies

README.md, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java
Added property for setting if branch name should be taken from build environment or not.
When using JGitflow maven plugin, then the property from Jenkins can not be used, so this will
open up for use with that plugin. The property will be true by default, so that old behavior is used.
- [Could not run with maven, but executed in Eclipse] Ensured that tests pass locally: `mvn clean package`
=> Issue #24 Add property for using CI branch name or not

src/main/java/pl/project13/maven/git/NativeGitProvider.java, src/test/java/pl/project13/maven/git/BigDiffTest.java
#336: fix hanging git subprocess in case of too much output on stdout/stderr.
The previous implementation read the output after the subprocess finished. In case the buffer is full, the subprocess waits infinitly.
Therefore the new implementation flushes the subprocess buffer by reading from stdout/stderr on background threads.
=> #336: fix hanging git subprocess in case of too much output on stdout/stderr.

src/main/java/pl/project13/maven/git/NativeGitProvider.java, src/test/java/pl/project13/maven/git/BigDiffTest.java
This is a follow up of #336 / #396 that deploys some simplifications and refactoring around the process launching.
=> #336 / #396: apply some refactoring to simplify the entire process launching

src/main/java/pl/project13/maven/git/PropertiesReplacer.java, src/main/java/pl/project13/maven/git/ReplacementProperty.java, src/test/java/pl/project13/maven/git/PropertiesReplacerTest.java
Allow for value to be empty in replacement property.
https://github.com/git-commit-id/maven-git-commit-id-plugin/issues/389
=> #389 allow replacementProperty value to be empty

README.md, src/main/java/pl/project13/maven/git/AheadBehind.java, src/main/java/pl/project13/maven/git/GitCommitPropertyConstant.java, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/main/java/pl/project13/maven/git/GitProvider.java, src/main/java/pl/project13/maven/git/JGitProvider.java, src/main/java/pl/project13/maven/git/NativeGitProvider.java, src/test/java/pl/project13/maven/git/AheadBehindTest.java, src/test/java/pl/project13/maven/git/JgitProviderAheadBehindTest.java, src/test/java/pl/project13/maven/git/NativeAndJGitProviderTest.java, src/test/java/pl/project13/maven/git/NativeProviderAheadBehindTest.java
Added git.branch.ahead and git.branch.behind, which could be used to verify synced with remote.
https://github.com/ktoso/maven-git-commit-id-plugin/issues/365
Since remote repository is required, no. Have done a bunch of manual local tests.
Just added the properties
Verified tests in Eclipse, not able to run mvn clean package, surefire complains about some class missing. Guess it's a jdk-issue for me.
=> 365 set ahead and behind properties

src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/main/java/pl/project13/maven/git/build/BuildServerDataProvider.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java, src/test/java/pl/project13/maven/git/GitIntegrationTest.java
This MR is a follow up to https://github.com/git-commit-id/maven-git-commit-id-plugin/pull/414 and includes the following:
- an additional cache check for the `git.build.host` to avoid unnecessary calls to `InetAddress.getLocalHost().getHostName()` which might be costly in a multi reactor build with many modules.
- ensure caching is working correctly if we are building a reactor projects with `injectAllReactorProjects=true` and also specify multiple execution with a different prefix for the plugin
Essentially the following in a multi reactor build and `injectAllReactorProjects=true`:
```xml
<plugin>
<groupId>pl.project13.maven</groupId>
<artifactId>git-commit-id-plugin</artifactId>
<version>${git-commit-id-version}</version>
<executions>
<execution>
<phase>initialize</phase> …
```
=> The new caching should work for reactor builds with different prefixes and injectAllReactorProjects=true

pom.xml
update com.fasterxml.jackson.core:jackson-databind 2.9.8 -> 2.9.9 as per [CVE-2019-12086](https://nvd.nist.gov/vuln/detail/CVE-2019-12086)
> A Polymorphic Typing issue was discovered in FasterXML jackson-databind 2.x before 2.9.9. When Default Typing is enabled (either globally or for a specific property) for an externally exposed JSON endpoint, the service has the mysql-connector-java jar (8.0.14 or earlier) in the classpath, and an attacker can host a crafted MySQL server reachable by the victim, an attacker can send a crafted JSON message that allows them to read arbitrary local files on the server. 
Based on this, this project does not seem to be affected in any way by this, but we still should update.
=> update com.fasterxml.jackson.core for CVE-2019-12086

README.md
The bold text formatting is not working as there are is no whitespace
line between the `<img>` tag  and the line of text describing the
license under which this plugins is being released.
This commit adds a line of whitespace so that the bold text is
formatted correctly, and it also fixes a typo in one of the hyperlinks.
I tried out your plugin today in my project and it is giving me something that I have been looking to use for a long time.
To show my gratitude, I have fixed a few problems in the main README.md file.  I will spend some more time reading over the rest of the documentation to get to know how to use your awesome plugin in more advanced situations.
=> Correct text bold formatting on license text

docs/using-the-plugin.md, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/main/java/pl/project13/maven/git/JGitProvider.java, src/main/java/pl/project13/maven/git/NativeGitProvider.java, src/test/java/pl/project13/maven/git/GitIntegrationTest.java
Version 3.0.0 started to look at "ahead" and "behind" branches. To do
so, it executes a Fetch command to the repo. This is unfortunate
because it introduces quite a bit of a delay when building, especially
when the machine is offline (e.g. on a plane). Also, it sets off
various alerts because the previous version did not do any remote
access.
This PR introduces an "offline" mode (disabled by default) that allows
turning off all commands that are trying to reach out to
remotes. Currently, that is only the fetch command which is executed
when trying to determine "ahead" and "behind". Any future operation
that is accessing remote repos should also check this flag.
=> Introduce "offline" mode

pom.xml, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/test/java/pl/project13/maven/git/UriUserInfoRemoverTest.java
This replaces the usage of `org.apache.http.client.utils.URIBuilder` with standard JDK API to get rid of the dependency
```
<dependency>
<groupId>org.apache.httpcomponents</groupId>
<artifactId>httpclient</artifactId>
<version>4.5.8</version>
</dependency>
```
This plugin has a dependency to apache `httpclient`. Apache `httpclient` has other transitive dependencies, e.g. `commons-logging`. Especially `commons-logging` can cause class loader issues when the user's project classpath contains already a dependency to `commons-logging`.
In my case i ran into:
```
118113 [ERROR] -----------------------------------------------------: org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one …
```
=> Remove the httpclient dependency

src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/java/pl/project13/maven/git/build/BuildServerDataProvider.java
The changes introduced in #185 do not cover the issue reported in #354 where a call to `getHostName()` may take a long time when getting the property `git.build.host`. Likewise, in certain (rare) cases, `TimeZone.getTimeZone()` may also have an impact upon performance when retrieving `git.build.time`. 
Depending on the number of projects, this may have a large effect on compile times as there may be numerous calls to the affected functions. A user should be able to filter these properties from being fetched so that build times can improve if this becomes an issue. This also further aligns with the changes in #185 to be more consistent with not fetching unused properties.
=> Add filtering capabilities for build server data.

src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/main/java/pl/project13/maven/git/build/BuildServerDataProvider.java
When checking for whether a key is within the `Properties` object, using `.contains` is equivalent of `.containsValue`, while the correct invocation is `.containsKey`. This also fixes the logging when saving the `Properties` object to the context.
=> Fix property caching when using injectAllReactorProjects.

src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
injectAllReactorProjects currently prints out each and every project that it injects the properties into. This change moves that to debug level logging only and instead only reports the number of projects that had this property injected into.
=> Make injectAllReactorProjects less verbose.

docs/using-the-plugin.md, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
Right now, because JGit doesn't support Git worktrees, I need to override `useNativeGit`
in the `pom.xml` of different projects, and it's easy to make a mistake and commit the
changes.
The proposed PR should allow to override this property from command-line via
`maven.gitcommitid.nativegit`, without modification of the `pom.xml`.
=> Allow to override useNativeGit from command line

src/main/java/pl/project13/jgit/DescribeResult.java, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/main/java/pl/project13/maven/git/GitDataProvider.java, src/main/java/pl/project13/maven/git/JGitProvider.java, src/main/java/pl/project13/maven/git/build/BambooBuildServerData.java, src/test/java/pl/project13/maven/git/BigDiffTest.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java
fixes some minor code inspection complains from intelliJ.
=> Some small code simplifications

docs/using-the-plugin.md
This seems to be a typo: the comment line should start with
=> wrong prefix of comment line

pom.xml
upgrade com.fasterxml.jackson.core:jackson-databind from 2.9.9.3 to 2.9.10 in order to fix [CVE-2019-14540](https://nvd.nist.gov/vuln/detail/CVE-2019-14540) and [CVE-2019-16335](https://nvd.nist.gov/vuln/detail/CVE-2019-16335)
=> upgrade jackson-databind to fix CVE-2019-14540 and CVE-2019-16335

docs/using-the-plugin.md, src/main/java/pl/project13/maven/git/build/AzureDevOpsBuildServerData.java, src/main/java/pl/project13/maven/git/build/BuildServerDataProvider.java
Populate "git.branch" and "git.build.number" for Azure DevOps
```
2019-10-01T09:20:52.8249155Z BUILD_BUILDNUMBER=20191001.1
2019-10-01T09:20:52.8249357Z BUILD_SOURCEBRANCHNAME=74902_build_info-and-pipelines_v3
...
2019-10-01T09:21:01.5141375Z [INFO] Collected git.build.number with value 20191001.1
...
2019-10-01T09:21:00.9696385Z [INFO] Using environment variable based branch name. BUILD_SOURCEBRANCHNAME = 74902_build_info-and-pipelines_v3
2019-10-01T09:21:00.9747110Z [INFO] Collected git.branch with value 74902_build_info-and-pipelines_v
```
=> Issue #438 Populate "git.branch" and "git.build.number" for Azure DevOps

maven/docs/using-the-plugin.md, maven/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
see: https://github.com/git-commit-id/maven-git-commit-id-plugin/issues/387
In most cases this doesn't change much, however for some this might be considered a behavioral change (and thus fits a major version change). In specific when `runOnlyOnce` is specified the plugin will run on the `first project` as specified in the `Reactor Build Order`.
As per debugging project:
```
$ mvn clean package -Pgit-with-parent
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Git Commit Id Plugin Maven Mojo Debugging
[INFO] submodule-one
[INFO] submodule-two
```
or with `--projects`
```
$ mvn clean package -Pgit-with-parent --projects submodule-one,submodule-two
[INFO] Scanning for projects...
[INFO] …
```
=> #387: make runOnlyOnce run on the first project (and make it work when maven's --projects param are specified)

core/src/main/java/pl/project13/core/cibuild/BuildServerDataProvider.java, core/src/main/java/pl/project13/core/cibuild/CircleCIBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/CircleCiBuildServerData.java
This adds support for CircleCI for this plugin. It's useful for getting branch name and revision number when running on CircleCI.
- [:x:] Added relevant integration or unit tests to verify the changes
- [:heavy_check_mark:] Update the Readme or any other documentation (including relevant Javadoc)
- [:heavy_check_mark:] Ensured that tests pass locally: `mvn clean package`
- [:heavy_check_mark:] Ensured that the code meets the current `checkstyle` coding style definition: `mvn clean verify -Pcheckstyle -Dmaven.test.skip=true -B`
I couldn't find any tests that tested that sort of thing, hence why I didn't add any.
=> Add support for CircleCI

core/src/main/java/pl/project13/core/cibuild/GitHubBuildServerData.java
I think this makes the code cleaner, and fixes a case where the returned branch name could be `refs/tags/<tagname>`.
=> Refactor for better readability, fix returning branch name based on tags

.github/workflows/default-tests.yml
Changes the GitHub workflow:
- Remove Java version matrix where it makes sense to only use one version, e.g. deploying snapshot
- Use consistent `mvn` command structure:
- `-B` as first flag
- `--file pom.xml` is redundant
- Remove "Package with Maven" step from `integration-test` because `clean install` should cover that already
- Use cache to not require GitHub to download Maven dependencies every time
Note that concurrent / parallel usage of the same cache might cause issues (see https://github.com/actions/cache/issues/189), however without it, a cache per job, per Java version / Maven version would be needed, for which the total cache size might become pretty large at some point.
You can see a successful run in my fork: https://github.com/Marcono1234/git-commit-id-maven-plugin/actions/ …
=> Simplify GitHub workflow, cache local Maven repository

README.md
#484: Clarify "Plugin compatibility with Maven"
Pretty much rerunning the tests from https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/295.
[comparision.bash.txt](https://github.com/git-commit-id/git-commit-id-maven-plugin/files/4639427/comparision.bash.txt)
[total_result.txt](https://github.com/git-commit-id/git-commit-id-maven-plugin/files/4639425/total_result.txt)
=> #484: Clarify "Plugin compatibility with Maven"

.github/workflows/default-tests.yml
The Java version matrix is not used anymore because the Java version is specified explicitly. I forgot to remove that in #486.
=> Remove unused Java version matrix from GitHub workflow

core/pom.xml, core/src/main/java/pl/project13/core/GitDataProvider.java, core/src/main/java/pl/project13/core/JGitProvider.java, core/src/main/java/pl/project13/core/NativeGitProvider.java, core/src/main/java/pl/project13/core/PropertiesFileGenerator.java, core/src/main/java/pl/project13/core/cibuild/GitHubBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/HudsonJenkinsBuildServerData.java, core/src/main/java/pl/project13/core/jgit/DescribeCommand.java, core/src/main/java/pl/project13/core/jgit/DescribeResult.java, core/src/main/java/pl/project13/core/jgit/JGitCommon.java, maven/pom.xml, maven/src/test/java/pl/project13/maven/git/FileSystemMavenSandbox.java, pom.xml
While Google Guava provides a lot of useful functionality, it is a rather heavy-weight dependency and was notorious for breaking backward-compatibility in the past.
There are only very few features from Google Guava used in `git-commit-id-maven-plugin` which could either be replaced by native Java 8 features (`Files.createParentDirs()`) or removed altogether (`@VisibleForTesting`).
=> Remove dependency on Google Guava

maven/src/test/java/pl/project13/maven/git/PropertiesFiltererTest.java
`Mockito.verifyZeroInteractions()` has been deprecated in favor of `Mockito.verifyNoInteractions()`.
=> Address Mockito deprecation warnings

core/src/main/java/pl/project13/core/cibuild/AwsCodeBuildBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/BuildServerDataProvider.java, maven/docs/using-the-plugin.md
Add support for fetching build information on [AWS CodeBuild](https://aws.amazon.com/codebuild/).
The available environment variables in the AWS CodeBuild build environment are listed at [Environment variables in build environments](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html).
=> Add support for AWS CodeBuild

maven/pom.xml
While JUnit 5.5.1 (API) is being declared as a dependency, the actual tests are all using JUnit 4.x.
=> Depend on JUnit 4.12 instead of JUnit 5.5.1

core/pom.xml, core/src/main/java/pl/project13/core/PropertiesFileGenerator.java
Jackson 2.9.x had and still gets a lot of CVEs because of how it handles deserialization of polymorphic types.
This has been fixed in Jackson 2.10.x and 2.11.x, so upgrading will safe this project from (unnecessary) security alerts.
* https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062
* https://medium.com/@cowtowncoder/jackson-2-10-safe-default-typing-2d018f0ce2ba
Additionally, explicitly block unsafe polymorphic base types with Jackson, just in case. 😉 
Refs #489
Closes #500
Refs #501
=> Upgrade to Jackson 2.11.1

core/src/main/java/pl/project13/core/GitDataProvider.java, core/src/main/java/pl/project13/core/PropertiesFileGenerator.java, core/src/main/java/pl/project13/core/cibuild/AwsCodeBuildBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/AzureDevOpsBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/BambooBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/BuildServerDataProvider.java, core/src/main/java/pl/project13/core/cibuild/CircleCiBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/GitlabBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/HudsonJenkinsBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/TeamCityBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/TravisBuildServerData.java, core/src/main/java/pl/project13/core/util/PropertyManager.java, maven/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, maven/src/main/java/pl/project13/maven/git/PropertiesReplacer.java
Changes the build system information to be conditionally set within the properties. In multi-threaded builds, without the optional put, a ConcurrentModificationException occurs as this information is written at the same time the object is being iterated over.
Fixes #469.
=> Build system information should be optionally set

core/src/main/java/pl/project13/core/cibuild/BuildServerDataProvider.java, maven/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
Untested :-)
Refs #509: Allow initial 'git.build.time' from 'project.build.outputTimestamp' to support reproducible builds
=> #509: Allow initial 'git.build.time' from 'project.build.outputTimestamp' to support reproducible builds

core/pom.xml
Includes bug fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=564202 which broke https://github.com/prestosql/presto builds
=> Update JGit dependency to 5.9.0.202009080501

core/src/main/java/pl/project13/core/GitDataProvider.java, maven/src/test/java/pl/project13/core/UriUserInfoRemoverTest.java
=> #519: fix an issue where special characters in the git URL simply yield: Illegal character in authority

core/pom.xml, core/src/main/java/pl/project13/core/GitDataProvider.java, core/src/main/java/pl/project13/core/NativeGitProvider.java, core/src/main/java/pl/project13/core/cibuild/AwsCodeBuildBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/AzureDevOpsBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/BambooBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/CircleCiBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/GitHubBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/GitlabBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/HudsonJenkinsBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/TeamCityBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/TravisBuildServerData.java, core/src/main/java/pl/project13/core/jgit/DescribeCommand.java, core/src/main/java/pl/project13/core/jgit/DescribeResult.java, core/src/main/java/pl/project13/core/jgit/JGitCommon.java, pom.xml
The [current build](https://github.com/git-commit-id/git-commit-id-maven-plugin/runs/1311745645) is failing due to 'broken' javadoc. This MR fixes those complaints.
=> fix javadoc generation for java 12 / 13

maven/pom.xml, maven/src/test/java/pl/project13/core/GitDataProviderTest.java, maven/src/test/java/pl/project13/core/jgit/DescribeCommandAbbrevIntegrationTest.java, maven/src/test/java/pl/project13/core/jgit/DescribeCommandIntegrationTest.java, maven/src/test/java/pl/project13/core/jgit/DescribeCommandTagsIntegrationTest.java, maven/src/test/java/pl/project13/core/jgit/DescribeResultTest.java, maven/src/test/java/pl/project13/core/jgit/JGitCommonIntegrationTest.java, maven/src/test/java/pl/project13/maven/git/BigDiffTest.java, maven/src/test/java/pl/project13/maven/git/ContainsKeyCondition.java, maven/src/test/java/pl/project13/maven/git/DoesNotContainKeyCondition.java, maven/src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java, maven/src/test/java/pl/project13/maven/git/GitCommitIdMojoTest.java, maven/src/test/java/pl/project13/maven/git/GitDirLocatorTest.java, maven/src/test/java/pl/project13/maven/git/GitPropertiesFileTest.java, maven/src/test/java/pl/project13/maven/git/GitSubmodulesTest.java, maven/src/test/java/pl/project13/maven/git/NaivePerformanceTest.java, maven/src/test/java/pl/project13/maven/git/NativeAndJGitProviderTest.java
fest-assert 2 once was assertj.  The authors differed in direction and the framework split.  fest-assert itself is long dead.  Version 2 never made release as a result and the migration as it were is incredibly easy as seen here and at least in one test set makes more logical sense.
=> [tests] Migrate off fest-assert to assertj

maven/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
=> #531: session.getProjectDependencyGraph() might be `null` when running the plugin from eclipse

core/src/main/java/pl/project13/core/cibuild/BitbucketBuildServerData.java, core/src/main/java/pl/project13/core/cibuild/BuildServerDataProvider.java, maven/docs/using-the-plugin.md
The Bitbucket Pipelines CI is not currently supported. This small change borrows from BambooBuilderServerData, and adds BitbucketBuilderServerData to support the CI. The documented environment variables are at [Variables and secrets](https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/)
=> Support Bitbucket Pipelines CI for build number and branch

core/src/main/java/pl/project13/core/GitCommitPropertyConstant.java, core/src/main/java/pl/project13/core/GitDataProvider.java, core/src/main/java/pl/project13/core/GitProvider.java, core/src/main/java/pl/project13/core/JGitProvider.java, core/src/main/java/pl/project13/core/NativeGitProvider.java, maven/docs/using-the-plugin.md, maven/src/test/java/pl/project13/maven/git/GitPropertiesFileTest.java, maven/src/test/java/pl/project13/maven/git/NaivePerformanceTest.java, maven/src/test/java/pl/project13/maven/git/NativeAndJGitProviderTest.java
Adds support for getting the properties `git.commit.time.author` and `git.commit.time.committer`.
=> add support for author and commiter times

core/src/main/java/pl/project13/core/NativeGitProvider.java
=> Explicitly hides commit sigs #548

.github/workflows/default-tests.yml, README.md, core/pom.xml, maven/pom.xml, pom.xml
=> Drop support for Java 8, Java 9 and Java 10 + Drop Maven 3.0.x

core/src/main/java/pl/project13/core/JGitProvider.java
port back git-commit-id/git-commit-id-plugin-core#8 to 4.9.x branch
=> get file store attr async to improve jgit startup performance

pom.xml, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
Requirement to fix https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/590
=> make use of git-commit-id-plugin-core:6.0.0-rc.2

.github/workflows/default-tests.yml, pom.xml, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
Brought all plugins up to date.  Adjusted the min maven so it can still run tests to confirm really old end of life maven versions still work.  Not this work is important given maven 3.9.0+ requirements and upcoming maven 4.
The release process will still complain with warnings if using maven 3.9.x.  This has to do with profiles in oss parent that should be removed and directly used as that is long obsolete as stated by nexus.  For now left it with just the in-line build plugins being fully addressed.
It would further be nice to get a release shortly after this although I see possibly some larger change for 6.x, possible that can drop back and be released or go as-is.  Either way this plugin current is vocal due to maven changes which only can be resolved by being up to date and releasing …
=> Bring plugins up to date, fix 2 javadoc issues, Require maven 3.2.5

pom.xml
- dependency to 3.6.0
- source to 3.3.0
- checkstyle to 3.3.0
- exec to 3.1.0
This leaves the general mvn clean install build with only javadoc related warning.  Site will still have many unfortunately but its getting better...
=> [pom] Update maven plugins to clear more warnings

src/main/java/pl/project13/maven/git/GitDirLocator.java, src/test/java/pl/project13/maven/git/GitDirLocatorTest.java
Fix https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/639
I have not tested this change end to end.
=> Resolve worktree .git files to repository .git directory

pom.xml
Maven required build xsd settings per maven standards.  This simply adds proper encoding xml marker and corrects site that will get redirected for the xsd.  This has no real impact on the build, just compliance feature.
=> [pom] Add encoding to pom and correct maven xsd location

src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
Enabling `injectAllReactorProjects` in large and old reactor projects allows to avoid repeatedly parsing the git history to retrieve the information.
In the apache/james-project enabling this property allowed to lower the time spent in git-commit-id from 39s[1] to 2s[2].
However, looking at the verbose logs one can see that the plugin keeps injecting the properties into every reactor project for every project where the plugin runs.
This commit aims to avoid reinjecting keys which have already been set in the context.
[1] https://ge.apache.org/s/xumcl7ztpkmhw/timeline?collapse-all&outcome=success,failed&view=by-type
[2] https://ge.apache.org/s/gpnevfknmdv5a/timeline?collapse-all&hide-timeline&outcome=success,failed&view=by-type
I'm not saying the fix is perfect, but hopefully it …
=> Only injects properties into every reactor project once

.github/workflows/default-tests.yml, pom.xml, src/main/java/pl/project13/maven/git/GitCommitIdMojo.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoTest.java, src/test/java/pl/project13/maven/git/NativeAndJGitProviderTest.java
#674: parse 'project.build.outputTimestamp' formatted as ISO 8601
=> #674: change timeformat from RFC822 to ISO 8601 to support maven's reproducible build feature

src/main/java/pl/project13/maven/git/GitDirLocator.java, src/test/java/pl/project13/maven/git/AvailableGitTestRepo.java, src/test/java/pl/project13/maven/git/BigDiffTest.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java, src/test/java/pl/project13/maven/git/GitDirLocatorTest.java, src/test/java/pl/project13/maven/git/GitIntegrationTest.java, src/test/java/pl/project13/maven/git/GitPropertiesFileTest.java, src/test/java/pl/project13/maven/git/GitSubmodulesTest.java, src/test/java/pl/project13/maven/git/NaivePerformanceTest.java, src/test/java/pl/project13/maven/git/NativeAndJGitProviderTest.java
See https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/701
=> #701: add testcases to for an issue with submodules

pom.xml
investigating Reproducible Builds issue https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/github/git-commit-id/README.md
see `mvn help:effective-pom -Dverbose -Psonatype-oss-release`
vs `mvn help:effective-pom -Dverbose -Pgpg`
particularly at maven-source-plugin level
=> use gpg profile on release, not sonatype-oss-release

pom.xml, src/test/java/pl/project13/core/jgit/DescribeCommandIntegrationTest.java, src/test/java/pl/project13/core/jgit/DescribeResultTest.java, src/test/java/pl/project13/maven/git/AheadBehindTest.java, src/test/java/pl/project13/maven/git/BigDiffTest.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoIntegrationTest.java, src/test/java/pl/project13/maven/git/GitCommitIdMojoTest.java, src/test/java/pl/project13/maven/git/GitIntegrationTest.java, src/test/java/pl/project13/maven/git/GitPropertiesFileTest.java, src/test/java/pl/project13/maven/git/GitSubmodulesTest.java, src/test/java/pl/project13/maven/git/NaivePerformanceTest.java, src/test/java/pl/project13/maven/git/NativeAndJGitProviderTest.java, src/test/java/pl/project13/maven/git/NativeProviderAheadBehindTest.java, src/test/java/pl/project13/maven/git/PropertiesFiltererTest.java, src/test/java/pl/project13/maven/git/PropertiesReplacerTest.java, src/test/java/pl/project13/maven/jgit/DescribeCommandAbbrevIntegrationTest.java, src/test/java/pl/project13/maven/jgit/DescribeCommandTagsIntegrationTest.java, src/test/java/pl/project13/maven/jgit/JgitProviderAheadBehindTest.java, src/test/java/pl/project13/maven/validation/ValidationMojoTest.java
=> #718: replace junit:junit:4.13.2:test with org.junit.jupiter:junit-jupiter-*:5.10.2:test

pom.xml
`--release` also verifies that only API from that Java version is used. Otherwise when building with a JDK newer than the target version it would be possible to accidentally use API not available in the target version.
This also fixes this warning which is currently printed during the build:
> [WARNING] system modules path not set in conjunction with -source 11
=> Use javac `--release` instead of `-source` & `-target`

src/main/java/pl/project13/maven/git/GitCommitIdMojo.java
=> #754: Fix an issue where empty git.properties had been generated in submodules when injectAllReactorProjects=true
